# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
    run_tests:
      docker:
        - image: circleci/node:10
        steps:
        - checkout
        - run:
            name: Install npm dependencies
            command:  |
              npm install --save
        - run:
            name: "Run Jest and Collect Coverage Reports"
          command: jest --collectCoverage=true
      - store_artifacts:
          path: coverage
workflows:
    build_test:
      jobs:
        - run_test